### ISSUE TITLE
Open source code

### ISSUE THREAD

**Issue by gaiyi7788** [Zongwei97/RFnet#1]
Excuse me, I think your work is very interesting. Do you have any recent plans for open source code? I'm looking forward to it. If there is no plan I will try to reproduce the work myself first. Thank you!

**Comment by Zongwei97** [comment]
Hi,
Thanks for your interest in your work.
I have just uploaded the code.
Maybe you can have a look there to find the module that interests you.

**Comment by gaiyi7788** [comment]
Thank you very much for opening the source code! I am going to learn it.
